name: ea-python-04-test
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  
  # Core scientific python
  - numpy
  - matplotlib
  - pandas

  # Earthpy
  - earthpy>=0.9.2

  # Jupyter Environment
  - papermill
  - autopep8
  - notebook
  - ipython
  - flake8-nb
